### ISSUE TITLE
Crash and lost elementor styles after update to version 1.4

### ISSUE THREAD

**Issue by delellis** [dudaster/ele-custom-skin#176]
When I updated to latest version of WorPress 5.4 and Elementor 2.9.7, Elementor Custom Skin crashes the website after deactivating Elementor Custom Skin 1.4 customizations of WP astra are lost. 

PHP 7.3 
I deactivated all themes and plugins but when I activate Elementor Custom Skin 1.4 the site crashes. 

**Related ticket:** https://wordpress.org/support/topic/crash-and-loses-styles-on-latest-version/

**Error log**

Stack trace:
#0 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/ele-custom-skin.php(41): require_once()
#1 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(287): elecs_add_skins(Object(Elementor\Widgets_Manager))
#2 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/winlaisy1/domains/neu.de/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(99): do_action(‘elementor/widge…’, Object(Elementor\Widgets_Manager))
#5 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(235): Elementor\Widgets_Manager in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 15
2020-04-08 00:24:21.430484 [NOTICE] [372579] [157.230.109.157:57444#APVH_neu.de:443] [STDERR] PHP Fatal error: Uncaught Error: Class ‘ElementorPro\Modules\Posts\Skins\Skin_Base’ not found in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php:15
Stack trace:
#0 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/ele-custom-skin.php(41): require_once()
#1 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(287): elecs_add_skins(Object(Elementor\Widgets_Manager))
#2 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/winlaisy1/domains/neu.de/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(99): do_action(‘elementor/widge…’, Object(Elementor\Widgets_Manager))
#5 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(235): Elementor\Widgets_Manager in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 15
2020-04-08 06:18:43.080181 [NOTICE] [442974] [230.122:44202:HTTP2-1#APVH_neu.de:443] [STDERR] PHP Fatal error: Uncaught Error: Class ‘ElementorPro\Modules\Posts\Skins\Skin_Base’ not found in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php:15
Stack trace:
#0 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/ele-custom-skin.php(41): require_once()
#1 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(287): elecs_add_skins(Object(Elementor\Widgets_Manager))
#2 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/winlaisy1/domains/neu.de/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(99): do_action(‘elementor/widge…’, Object(Elementor\Widgets_Manager))
#5 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(235): Elementor\Widgets_Manager in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 15
2020-04-08 06:18:45.915902 [NOTICE] [442974] [230.122:44202:HTTP2-3#APVH_neu.de:443] [STDERR] PHP Fatal error: Uncaught Error: Class ‘ElementorPro\Modules\Posts\Skins\Skin_Base’ not found in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php:15
Stack trace:
#0 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/ele-custom-skin.php(41): require_once()
#1 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(287): elecs_add_skins(Object(Elementor\Widgets_Manager))
#2 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/winlaisy1/domains/neu.de/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(99): do_action(‘elementor/widge…’, Object(Elementor\Widgets_Manager))
#5 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(235): Elementor\Widgets_Manager in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 15
2020-04-08 06:31:17.383109 [NOTICE] [442975] [230.122:37685:HTTP2-1#APVH_neu.de:443] [STDERR] PHP Fatal error: Uncaught Error: Class ‘ElementorPro\Modules\Posts\Skins\Skin_Base’ not found in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php:15
Stack trace:
#0 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/ele-custom-skin.php(41): require_once()
#1 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(287): elecs_add_skins(Object(Elementor\Widgets_Manager))
#2 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/winlaisy1/domains/neu.de/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(99): do_action(‘elementor/widge…’, Object(Elementor\Widgets_Manager))
#5 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(235): Elementor\Widgets_Manager in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 15
2020-04-08 06:44:52.229811 [NOTICE] [356146] [230.122:48534:HTTP2-1#APVH_neu.de:443] [STDERR] PHP Fatal error: Uncaught Error: Class ‘ElementorPro\Modules\Posts\Skins\Skin_Base’ not found in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php:15
Stack trace:
#0 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/ele-custom-skin.php(41): require_once()
#1 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(287): elecs_add_skins(Object(Elementor\Widgets_Manager))
#2 /home/winlaisy1/domains/neu.de/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/winlaisy1/domains/neu.de/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(99): do_action(‘elementor/widge…’, Object(Elementor\Widgets_Manager))
#5 /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(235): Elementor\Widgets_Manager in /home/winlaisy1/domains/neu.de/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 15
2020-04-09 08:44:09.970701 [INFO] [228267] [122:35327:HTTP2-17#APVH_neu.de:443] Abort request processing by PID:53472, kill: 1, begin time: 0, sent time: 0, req processed: 1
2020-04-09 08:50:10.845151 [INFO] [228267] [230.122:39246:HTTP2-15#APVH_neu.de:443] Abort request processing by PID:295085, kill: 1, begin time: 0, sent time: 0, req processed: 0
2020-04-09 08:50:14.954617 [INFO] [228267] [230.122:39246:HTTP2-65#APVH_neu.de:443] Abort request processing by PID:295743, kill: 1, begin time: 0, sent time: 0, req processed: 1

![elementor](https://user-images.githubusercontent.com/13867348/78898742-969eb580-7a74-11ea-8516-07c15696f84f.png)

**Comment by delellis** [comment]
I was able to solve it: The problem was the missing post content widget in my templates... I had to re-apply it manually.

https://docs.elementor.com/article/428-post-content-widget
