### ISSUE TITLE
Plugin update fail

### ISSUE THREAD

**Issue by haiyrhobo** [dudaster/ele-custom-skin#329]
Hi, i tried updating the plugin and this error appeared....
What do i need to do to fix it?

Thanks

An error of type E_ERROR was caused in line 39 of the file /home/ordesign/cider.ordesign.me/wp-content/plugins/ele-custom-skin/theme-builder/conditions/loop.php. Error message: Uncaught Error: Class 'ElementorPro\Core\Utils' not found in /home/ordesign/cider.ordesign.me/wp-content/plugins/ele-custom-skin/theme-builder/conditions/loop.php:39 Stack trace: #0 /home/ordesign/cider.ordesign.me/wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php(66): ECS_Loop_Conditions->register_sub_conditions() #1 /home/ordesign/cider.ordesign.me/wp-content/plugins/ele-custom-skin/theme-builder/conditions/loop.php(67): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct() #2 /home/ordesign/cider.ordesign.me/wp-includes/class-wp-hook.php(288): {closure}(Object(ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager)) #3 /home/ordesign/cider.ordesign.me/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #4 /home/ordesign/cider.ordesign.me/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /home/ordesign/cider.ordesign.me/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(239): do_actio

**Comment by dudaster** [comment]
You need to update elementor first
