### ISSUE TITLE
Elementor Custom skin plugin is not working with latest version of Wordpress

### ISSUE THREAD

**Issue by Gavsterbro** [dudaster/ele-custom-skin#465]
Hi, I have a custom loop set up that is not showing on the home page anymore. 
This used to be visible and now I am unable to edit with elementor page builder as I get loading wheel of death. 

Once I deactivate the plugin I'm able to use elementor. 
The issue on the home page can be viewed here: http://www.glendyrdadeproperties.co.za/ 
The issue for the rentals properties not showing is here: http://www.glendyrdadeproperties.co.za/rentals/

Please advise how I can fix this issue. 

Many thanks

**Comment by julianwitzel** [comment]
I have something similar. For me the whole page is not loading anymore. But only in Safari. Very strange

**Comment by ShaonPro** [comment]
Hey, @Gavsterbro 
I Hope You Are doing Well, You can Update your Elementor and Elementor Pro to the latest Version And Try with Deactivated Your **Elementor Custom skin Pro** Plugin. That's My Help Your Problem. Thanks

**Comment by Gavsterbro** [comment]
Hi @ShaonPro . Thank you for the response. I did try this previously and it still wont show unfortunately. 
I read an article to say that I should try run the older version of Wordpress but that is not working either.

**Comment by dudaster** [comment]
Try use other Loop templates:

1. Disable ECS
2. Change the skin to classic.
3. Enable ECS
4. Make A simple Loop Template (do not copy paste the old one)
5. Choose custom skin with the new made template.

Also make sure is not an plugin conflict issue.

**Comment by Gavsterbro** [comment]
Thans @dudaster .

Forgive me I'm relatively new to this. What does ECS stand for? 
I originally built the site on a test link then copied it across to the live domain and deleted the test. will this cause issues perhaps?

**Comment by dudaster** [comment]
Sorry : **E**le**C**ustom**S**kin

**Comment by Gavsterbro** [comment]
Ah, of course. silly me!

**Comment by Gavsterbro** [comment]
Ill try your points and will revert shortly. Thanks once again

**Comment by Gavsterbro** [comment]
@dudaster I have tried
 your suggestions and numerous others I found but all I get now is a grey loading screen from elementor. I have tried deactivating all the plugins one by one but only when I deactivate ECS does it work again. Any other ideas? 

Many thanks

**Comment by Gavsterbro** [comment]
<img width="556" alt="Screenshot 2021-04-02 at 11 46 52" src="https://user-images.githubusercontent.com/42736494/113409419-20900e80-93a9-11eb-90c4-de61a0cfe233.png">
 SO upon inspection, I have the following errors. Are these errors to do with hosting? Any idea on how to fix these?

**Comment by graffictetd** [comment]
me too and i have many sites and pages using it- in ,y customers website and there is no update- it must have an update i can not now redo all my website work :(

**Comment by dudaster** [comment]
I need you to post an php error log here so I can help you.

**Comment by dudaster** [comment]
> <img alt="Screenshot 2021-04-02 at 11 46 52" width="556" src="https://user-images.githubusercontent.com/42736494/113409419-20900e80-93a9-11eb-90c4-de61a0cfe233.png">
> 
> SO upon inspection, I have the following errors. Are these errors to do with hosting? Any idea on how to fix these?

Make sure is not a HTTPS issue!

**Comment by Gavsterbro** [comment]
Thanks @dudaster. great support! I have sorted the HTTPS issue too.

**Comment by graffictetd** [comment]
> I need you to post an php error log here so I can help you.

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.28
	PHP Version: 7.0.33
	PHP Max Input Vars: 10240
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://smartfinance.co.il
	Home URL: https://smartfinance.co.il
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/%category%/
	Language: he-IL
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.3.0.1587554547
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.9.5
		Author: Elliot Condon

	Advanced Post Queries
		Version: 1.0.15
		Author: Shabti Kaplan

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.9.0
		Author: WebDevStudios

	Duplicate Page
		Version: 4.4
		Author: mndpsingh287

	DynamicConditions
		Version: 1.5.1
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	Insert Headers and Footers
		Version: 1.5.0
		Author: WPBeginner

	Join.chat
		Version: 4.1.12
		Author: Creame

	Lara's Google Analytics
		Version: 3.3.3
		Author: XtraOrbit Web development SRL

	LiteSpeed Cache
		Version: 3.6.4
		Author: LiteSpeed Technologies

	One Click Accessibility
		Version: 2.0.3
		Author: One Click Accessibility

	Redirection
		Version: 5.1.1
		Author: John Godley

	Search Exclude
		Version: 1.2.6
		Author: Roman Pronskiy

	Simple Custom Post Order
		Version: 2.5.4
		Author: Colorlib

	Webcraftic Robin image optimizer
		Version: 1.5.3
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	WP Mail SMTP
		Version: 2.7.0
		Author: WPForms

	Yoast SEO
		Version: 16.1.1
		Author: Team Yoast


== Must-Use Plugins ==
	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen


== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: compatible

== אלמנטור פרו - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 14
		archive-posts : 2
		breadcrumbs : 13
		button : 11
		divider : 5
		facebook-page : 1
		form : 2
		global : 1
		heading : 26
		image : 5
		posts : 18
		search-form : 1
	footer : 1
		button : 2
		heading : 4
		icon : 1
		icon-list : 4
		image : 1
		social-icons : 1
		text-editor : 2
	header : 1
		button : 1
		heading : 1
		icon-list : 3
		image : 1
		nav-menu : 1
		search-form : 1
	loop : 16
		button : 4
		call-to-action : 1
		heading : 4
		icon : 1
		icon-list : 2
		image : 5
		spacer : 2
		star-rating : 1
		text-editor : 6
		theme-post-excerpt : 1
		theme-post-featured-image : 2
		theme-post-title : 5
		toggle : 1
		video : 5
	page : 6
		breadcrumbs : 2
		button : 9
		divider : 5
		form : 2
		global : 1
		heading : 23
		icon-list : 4
		image : 3
		media-carousel : 1
		posts : 11
		slides : 1
		spacer : 1
		text-editor : 8
		theme-post-content : 1
		video : 1
	popup : 1
		form : 1
		heading : 2
		icon-list : 1
	section : 8
		breadcrumbs : 3
		button : 4
		form : 1
		global : 2
		heading : 9
		icon-box : 5
		image : 1
		social-icons : 1
		spacer : 1
		theme-post-featured-image : 1
	single : 13
		breadcrumbs : 10
		button : 3
		divider : 1
		global : 1
		heading : 22
		icon : 1
		icon-list : 3
		image : 5
		post-info : 1
		post-navigation : 6
		posts : 5
		share-buttons : 1
		spacer : 2
		star-rating : 1
		text-editor : 7
		theme-post-content : 4
		theme-post-excerpt : 1
		theme-post-featured-image : 4
		video : 1
	widget : 0
		button : 326
		divider : 284
		form : 241
		media-carousel : 3
	wp-post : 0
		breadcrumbs : 2
		button : 4
		form : 1
		global : 1
		heading : 12
		icon-list : 4
		image : 2
		posts : 2
		text-editor : 4
		theme-post-featured-image : 2
	wp-page : 5
		animated-headline : 1
		blockquote : 1
		button : 5
		countdown : 1
		divider : 2
		form : 1
		global : 3
		heading : 9
		icon-list : 3
		image : 2
		posts : 7
		slides : 1
		text-editor : 6
		video : 1
	single-post : 1
		breadcrumbs : 1
		heading : 1
		post-navigation : 1
		text-editor : 1
		video : 1
	search-results : 1
		archive-posts : 1
		breadcrumbs : 1
		heading : 1
	error-404 : 1
		breadcrumbs : 1
		heading : 4
		icon-list : 1
		image : 2
		search-form : 1


== Log ==
	
JS: showing 15 of 15JS: 2020-09-09 08:21:48 [error X 1][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3686\") has already been destroyed and cannot be used. 
JS: 2020-09-09 08:23:09 [error X 1][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view110\") has already been destroyed and cannot be used. 
JS: 2020-09-09 10:47:53 [error X 3][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view301\") has already been destroyed and cannot be used. 
JS: 2020-09-09 11:00:31 [error X 9][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.5:2:470469] Cannot read property \'document\' of undefined 
JS: 2020-09-15 10:20:21 [error X 1][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view304\") has already been destroyed and cannot be used. 
JS: 2020-09-15 10:51:38 [error X 20][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view300\") has already been destroyed and cannot be used. 
JS: 2020-09-15 11:49:50 [error X 2][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view294\") has already been destroyed and cannot be used. 
JS: 2020-09-15 12:39:19 [error X 2][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.0.5:2:60281] Cannot read property \'attributes\' of undefined 
JS: 2020-09-29 10:06:30 [error X 1][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view175\") has already been destroyed and cannot be used. 
JS: 2020-09-29 10:06:42 [error X 1][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view835\") has already been destroyed and cannot be used. 
JS: 2020-11-07 09:51:58 [error X 2][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view314\") has already been destroyed and cannot be used. 
JS: 2021-01-17 13:26:37 [error X 4][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view317\") has already been destroyed and cannot be used. 
JS: 2021-01-19 09:13:09 [error X 7][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view323\") has already been destroyed and cannot be used. 
JS: 2021-01-19 09:50:54 [error X 1][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view291\") has already been destroyed and cannot be used. 
JS: 2021-01-19 09:51:04 [error X 1][https://dev.smartfinance.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view192\") has already been destroyed and cannot be used. 

PHP: showing 6 of 6PHP: 2020-09-15 10:44:21 [error X 1][/home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor/includes/template-library/sources/local.php::1086] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/smartfin/dev.smartfinance.co.il/wp-includes/class-wp-hook.php on line 289 and defined in /home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor/includes/template-library/sources/local.php:1086
Stack trace:
#0 /home/smartfin/dev.smartfinance.co.il/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(3071, Object(stdClass))
#1 /home/smartfin/dev.smartfinance.co.il/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/smartfin/dev.smartfinance.co.il/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/smartfin/dev.smartfinance.co.il/wp-includes/post.php(4153): do_action('save_post', 3071, Object(stdClass), true)
#4 /home/smartfin/dev.smartfinance.co.il/wp-includes/post.php(4244): wp_insert_post(Array, false)
#5 /home/smartfin/dev.smartfinance.co.il/wp-content [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-15 12:49:13 [notice X 21][/home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-27 07:51:16 [notice X 2][/home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 14:58:23 [notice X 1][/home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::911] Undefined index: pagination [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-09 23:28:44 [notice X 1][/home/smartfin/public_html/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-14 12:23:03 [notice X 2][/home/smartfin/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 212020-09-27 19:39:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.0.2',
  'to' => '3.0.5',
)]
2021-01-17 13:06:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.0.10',
  'to' => '3.0.16',
)]
2021-01-17 13:07:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.0.5',
  'to' => '3.0.9',
)]
2021-03-16 11:44:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.0.16',
  'to' => '3.1.4',
)]
2021-03-16 11:50:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.0.9',
  'to' => '3.1.1',
)]
2021-03-16 14:58:20 [info] elementor-pro::elementor_pro_updater Started 
2021-03-16 14:58:20 [info] אלמנטור פרו/Upgrades - _v_3_1_0_media_carousel Start  
2021-03-16 14:58:20 [info] אלמנטור פרו/Upgrades - _v_3_1_0_media_carousel Finished 
2021-03-16 14:58:20 [info] אלמנטור פרו/Upgrades - _v_3_1_0_reviews Start  
2021-03-16 14:58:21 [info] אלמנטור פרו/Upgrades - _v_3_1_0_reviews Finished 
2021-03-16 14:58:21 [info] אלמנטור פרו/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-03-16 14:58:21 [info] אלמנטור פרו/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-03-16 14:58:21 [info] אלמנטור פרו/Upgrades - _v_3_1_0_slides Start  
2021-03-16 14:58:22 [info] אלמנטור פרו/Upgrades - _v_3_1_0_slides callback needs to run more 3 times 
2021-03-16 14:58:22 [info] אלמנטור פרו/Upgrades - _v_3_1_0_slides Start (2 of 4, 50%) 
2021-03-16 14:58:22 [info] אלמנטור פרו/Upgrades - _v_3_1_0_slides Start (3 of 4, 75%) 
2021-03-16 14:58:22 [info] אלמנטור פרו/Upgrades - _v_3_1_0_slides Start (4 of 4, 100%) 
2021-03-16 14:58:23 [info] אלמנטור פרו/Upgrades - _v_3_1_0_slides Finished 
2021-03-16 14:58:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.0.9',
  'to' => '3.2.0',
)]
2021-04-09 17:47:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.2.0',
  'to' => '3.2.1',
)]

**Comment by graffictetd** [comment]
> I need you to post an php error log here so I can help you.

PHP: showing 6 of 6
PHP: 2020-09-15 10:44:21 [error X 1][/home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor/includes/template-library/sources/local.php::1086] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/smartfin/dev.smartfinance.co.il/wp-includes/class-wp-hook.php on line 289 and defined in /home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor/includes/template-library/sources/local.php:1086
Stack trace:
#0 /home/smartfin/dev.smartfinance.co.il/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(3071, Object(stdClass))
#1 /home/smartfin/dev.smartfinance.co.il/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/smartfin/dev.smartfinance.co.il/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/smartfin/dev.smartfinance.co.il/wp-includes/post.php(4153): do_action('save_post', 3071, Object(stdClass), true)
#4 /home/smartfin/dev.smartfinance.co.il/wp-includes/post.php(4244): wp_insert_post(Array, false)
#5 /home/smartfin/dev.smartfinance.co.il/wp-content [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-15 12:49:13 [notice X 21][/home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-27 07:51:16 [notice X 2][/home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 14:58:23 [notice X 1][/home/smartfin/dev.smartfinance.co.il/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::911] Undefined index: pagination [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-09 23:28:44 [notice X 1][/home/smartfin/public_html/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-14 12:23:03 [notice X 2][/home/smartfin/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by dudaster** [comment]
Can you please try this beta to see if it fixes the issue?

https://github.com/dudaster/ele-custom-skin/issues/476

**Comment by Biodynamic90** [comment]
@Gavsterbro I have a similar issue: or two: My homepage is divided into 3 sections. Everything worked fine until yesterday, then suddenly the last section stopped showing the images. I also noticed elementor editor works for every page but not for my homepage. I deactivated Ele custom skin and the elementor works again. But my blog page and images were made using this plugin. Really don't know what to do. Noticed this was over 2 years ago. Does anyone have any tips? Or should I clarify further with anything else?
