### ISSUE TITLE
Site completely breaks if Ele custom pro is activated

### ISSUE THREAD

**Issue by Mediaweeze** [dudaster/ele-custom-skin#510]
My site completely broke today and will only work if ele custom skin pro is deactivated.

Fatal error: Uncaught Error: Call to a member function get_main_meta() on null in /home/customer/www/fittleworthgallery.co.uk/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:448 Stack trace: #0 /home/customer/www/fittleworthgallery.co.uk/public_html/wp-content/plugins/ele-custom-skin-pro/modules/display-conditions.php(57): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->get_document_conditions(NULL) #1 /home/customer/www/fittleworthgallery.co.uk/public_html/wp-content/plugins/ele-custom-skin-pro/modules/display-conditions.php(23): ECS_Conditions_Manager->cache_conditions() #2 /home/customer/www/fittleworthgallery.co.uk/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(546): ECS_Conditions_Manager->__construct() #3 /home/customer/www/fittleworthgallery.co.uk/public_html/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render() #4 /home/customer/www/fittleworthgallery.co.uk/public_ in /home/customer/www/fittleworthgallery.co.uk/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php on line 448

**Comment by dudaster** [comment]
Usually this happens when you upgrade from Elementor < 2.8.0 vesion. But all you need to do is to deactivate ECS and update the Elementor first and activate ECS again.

Does this solves your problem?

**Comment by Mediaweeze** [comment]
Hi Liviu,

No, I tried that, I even tried installing back to earlier versions but it
didn't fix the issue.

**Comment by dudaster** [comment]
Please update to the latest Elementor and Pro and to the latest Ele Custom Skin (3.1.0) and Pro(3.1.0) (they should be both active).

**Comment by Mediaweeze** [comment]
Hi,

Ele Custom SKin is 3.1.0 Ele custom skin Pro is 3.0.0 (with no option to
update) Elementor pro is the latest version.

**Comment by dudaster** [comment]
Search the email from gumroad and you'll find an link to download the latest pro version. Let me know if it fixes the issue!

**Comment by Mediaweeze** [comment]
No still broken.

**Comment by dudaster** [comment]
Can you provide me access to the admin? My email is dudaster

**Comment by Mediaweeze** [comment]
Done

**Comment by dudaster** [comment]
Didn't receive anything on email please make sure you got it right!

**Comment by dudaster** [comment]
Received now

**Comment by dudaster** [comment]
I think the issue is from this plugin: dynamicconditions

**Comment by dudaster** [comment]
I'll still investigate.

**Comment by Mediaweeze** [comment]
I did deactivate that to see if it was but it didn't fix anything

**Comment by dudaster** [comment]
I've disabled conditional display and it is working... I don't know why it is happening only to you... I'll research some more.

**Comment by alfiefeatherstone** [comment]
I've had something similar, if less serious, happen - while ele custom is activated the elementor editor doesn't work.

This happens when elementor and ele custom are the only 2 plugins active.

**Comment by imryaaan** [comment]
The same thing happens to me, I only have Elementor Pro 3.2.2 and Ele custom skin 3.1.0 active and the Elementor editor stops working.

I can only edit widgets by clicking on them through the navigator window.

**Comment by Mediaweeze** [comment]
The problem is still occurring on another page so I have had to
deactivate ele custom skin pro again...
Best wishes,

*Louise Catterall *

m: +44 (0) 7834454646
w: mediabreeze.co.uk  <http://mediabreeze.co.uk>

33 Madehurst Road, Madehurst, Arundel, West Sussex, BN18 0NU

<https://www.mediabreeze.co.uk/>

*follow us:**  <https://www.instagram.com/mediaweeze/>
<http://linked.com/company/mediabreezedesign>
<https://www.facebook.com/Mediabreeze> * <https://twitter.com/mediabreeze>

**Comment by Mediaweeze** [comment]
> I've disabled conditional display and it is working... I don't know why it is happening only to you... I'll research some more.

Hi, is there any update on this?

**Comment by askwpgirl** [comment]
If you are using a site using custom coding by gumroad, that could be problem. Their coding is not great and caused endless issues on another site. I'd recommend creating a staging site and getting rid of all custom gumroad coding and then testing updates.

**Comment by dudaster** [comment]
@askwpgirl Do you have any proof that the code is altered by gumroad?

**Comment by Mediaweeze** [comment]
There is no custom code by Gumroad on the site.

**Comment by askwpgirl** [comment]
Okay, someone mentioned gumroad above, so thought it was worth checking considering the oddness of the issue.

**Comment by dudaster** [comment]
Elementor is a complex piece of code and in certain circumstances behaves differently.

**Comment by Radoxtein** [comment]
I tried something and it worked. First I deactivated the elementor pro plugin, then I deleted the ele custom skin plugin, next I added the ele custom skin back and finally activated the elementor pro plugin ... Follow this step it might help
