### ISSUE TITLE
Fatal Error when logging in

### ISSUE THREAD

**Issue by DigitalBerry** [dudaster/ele-custom-skin#665]
I'm getting this error on one of my largest client sites, where some users are unable to access the WP dashboard after login. When I deactivate ECS plugin, users are able to login.

Is anyone able to get this issue fixed ASAP, as it's causing havoc with my business!

I'm running all latest versions of ECS, ECSPro and Elementor and EPro.

`Fatal error: Uncaught TypeError: Unsupported operand types: int - string in /nas/content/live/happrod/wp-content/plugins/ele-custom-skin/includes/ecs-notices.php:95 Stack trace: #0 /nas/content/live/happrod/wp-content/plugins/ele-custom-skin/includes/ecs-notices.php(105): ecs_days_old() #1 /nas/content/live/happrod/wp-content/plugins/ele-custom-skin/includes/ecs-notices.php(81): ecs_load_notifications() #2 /nas/content/live/happrod/wp-includes/class-wp-hook.php(303): ecs_check_for_notification('') #3 /nas/content/live/happrod/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #4 /nas/content/live/happrod/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #5 /nas/content/live/happrod/wp-settings.php(578): do_action('init') #6 /nas/content/live/happrod/wp-config.php(134): require_once('/nas/content/li...') #7 /nas/content/live/happrod/wp-load.php(50): require_once('/nas/content/li...') #8 /nas/content/live/happrod/wp-admin/admin.php(34): require_once('/nas/content/li...') #9 /nas/content/live/happrod/wp-admin/index.php(10): require_once('/nas/content/li...') #10 {main} thrown in /nas/content/live/happrod/wp-content/plugins/ele-custom-skin/includes/ecs-notices.php on line 95`

**Comment by DigitalBerry** [comment]
Hello?

@dudaster can you tell me if this error is a plugin one, or somewhere else? I kinda need to allow my clients to be able to login to their own site, and it's this plugin's error blocking it at the moment.

**Comment by dudaster** [comment]
I don't know what triggered that error try to comment line 95 in this file:
`/nas/content/live/happrod/wp-content/plugins/ele-custom-skin/includes/ecs-notices.php:95`

**Comment by DigitalBerry** [comment]
A bit if further insight...

If I add a new User, they can login fine. It's all of the existing users (expect my own Admin) who can't login unless I deactivate ECS plugin. We have 135+ User accounts linked to 1000+ blog posts, so "re-adding" them is not an option...

Please help!

**Comment by dudaster** [comment]
Also please provide "Copy & Paste info" from:
`/wp-admin/admin.php?page=elementor-system-info` so I can recreate it on my side to fix it for later versions.

**Comment by DigitalBerry** [comment]
This is line 95..

return round((time() - get_user_meta( $user_id, $nstall ,true )) / 86400);

I commented it out and now can login in. Can I leave this line commented out?

**Comment by dudaster** [comment]
Yes you can.

**Comment by DigitalBerry** [comment]
> 

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '38', Revision '3692a61' v5.7.35-38
	PHP Version: 8.0.14
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: https://hapstage.wpengine.com
	Home URL: https://hapstage.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hall & Partners
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

== Active Plugins ==
	Admin Menu Editor
		Version: 1.10
		Author: Janis Elsts

	Advanced Custom Fields
		Version: 5.11.4
		Author: Delicious Brains

	Advanced Custom Fields Multilingual
		Version: 1.9.5
		Author: OnTheGoSystems

	Advanced Custom Fields PRO
		Version: 5.11.4
		Author: Delicious Brains

	Advanced Scripts
		Version: 2.3.3
		Author: Clean Plugins

	Atarim - Client Interface Plugin
		Version: 2.6.0
		Author: Atarim

	Custom Post Type UI
		Version: 1.10.1
		Author: WebDevStudios

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.2.11
		Author: Dynamic.ooo

	Ele Custom Skin
		Version: 3.1.4
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.1
		Author: Dudaster.com

	Elementor
		Version: 3.5.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	Happy Elementor Addons
		Version: 3.4.0
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 2.2.2
		Author: weDevs

	HappyFiles Pro
		Version: 1.4.1
		Author: Codeer

	JetSmartFilters
		Version: 2.3.7
		Author: Crocoblock

	OoohBoi Steroids for Elementor
		Version: 1.8.2
		Author: OoohBoi

	Perfmatters
		Version: 1.8.1
		Author: forgemedia

	Permalink Manager Lite
		Version: 2.2.14
		Author: Maciej Bis

	Piotnet Addons For Elementor Pro
		Version: 6.4.21
		Author: Piotnet Team

	ProfilePress
		Version: 3.2.6
		Author: ProfilePress Team

	Really Simple SSL
		Version: 5.2.2
		Author: Really Simple Plugins

	Search Exclude
		Version: 1.2.6
		Author: Roman Pronskiy

	Simple 301 Redirects
		Version: 2.0.6
		Author: WPDeveloper

	Temporary Login Without Password
		Version: 1.7.1
		Author: StoreApps

	The Plus Addons for Elementor
		Version: 5.0.5
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.0.7
		Author: POSIMYTH

	White Label CMS
		Version: 2.2.6
		Author: www.videousermanuals.com

	WPML Media
		Version: 2.7.0
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.5.2
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.0
		Author: OnTheGoSystems


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WPE ElasticPress Autosuggest Logger
		Version: 1.0.0
		Author: WP Engine

	WP Engine Cache Plugin
		Version: 1.0.5
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine


== Elements Usage ==
	
	archive : 16
		archive-posts : 4
		button : 1
		divider : 1
		form : 1
		heading : 12
		icon : 1
		jet-smart-filters-pagination : 2
		jet-smart-filters-remove-filters : 2
		jet-smart-filters-select : 3
		lottie : 3
		posts : 7
		spacer : 1
		text-editor : 2
	footer : 3
		button : 1
		heading : 5
		icon : 5
		icon-list : 3
		shortcode : 1
		text-editor : 4
	header : 3
		button : 1
		icon : 1
		lottie : 1
		nav-menu : 1
		theme-site-logo : 1
	loop : 33
		heading : 12
		icon : 2
		image : 5
		post-info : 2
		text-editor : 4
		theme-post-excerpt : 1
		theme-post-featured-image : 2
	page : 51
		button : 2
		form : 1
		heading : 24
		image : 7
		posts : 5
		share-buttons : 1
		social-icons : 1
		spacer : 2
		text-editor : 11
	popup : 7
		button : 1
		form : 2
		heading : 3
		image : 1
		nav-menu : 1
		text-editor : 2
	section : 33
		accordion : 1
		form : 2
		ha-scrolling-image : 1
		heading : 15
		icon : 3
		lottie : 5
		spacer : 1
		text-editor : 6
		toggle : 1
	widget : 0
		form : 3
		ha-animated-text : 1
	wp-post : 3
		text-editor : 2
	wp-page : 142
		accordion : 6
		button : 50
		divider : 22
		flip-box : 7
		form : 21
		ha-advanced-tabs : 4
		ha-animated-text : 4
		ha-card : 11
		heading : 428
		html : 3
		icon : 117
		icon-box : 37
		icon-list : 10
		image : 69
		image-carousel : 1
		lottie : 71
		posts : 28
		spacer : 2
		text-editor : 279
		toggle : 7
		video : 3
	single-post : 12
		author-box : 3
		form : 1
		heading : 18
		icon : 4
		image : 2
		lottie : 4
		posts : 3
		share-buttons : 2
		social-icons : 3
		table-of-contents : 2
		text-editor : 5
		theme-post-content : 4
		toggle : 2
	single-page : 17
		accordion : 1
		button : 4
		divider : 1
		dyncontel-acf : 1
		form : 1
		google_maps : 2
		heading : 26
		icon : 9
		image : 1
		lottie : 5
		menu-anchor : 1
		posts : 1
		spacer : 2
		text-editor : 14
		theme-post-content : 1
	search-results : 3
		archive-posts : 1
		theme-archive-title : 1
	error-404 : 3
		button : 1
		heading : 1
		text-editor : 1


== Elementor Experiments ==
	Optimised DOM Output: Inactive
	Improved asset loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility improvements: Inactive
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive


== Log ==
	
Log: showing 20 of 342022-01-04 11:17:07 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Finished 
2022-01-04 11:17:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.2.5',
  'to' => '2.2.9',
)]
2022-01-04 11:17:08 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-04 11:17:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.3',
)]
2022-01-11 13:41:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.2.9',
  'to' => '2.2.10',
)]
2022-01-11 13:41:57 [info] dynamic-content-for-elementor::dce_updater Started 
2022-01-11 13:41:57 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Start  
2022-01-11 13:41:58 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default callback needs to run more 2 times 
2022-01-11 13:41:58 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Start (2 of 3, 67%) 
2022-01-11 13:41:59 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Start (3 of 3, 100%) 
2022-01-11 13:42:00 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Finished 
2022-01-11 13:42:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.2.9',
  'to' => '2.2.10',
)]
2022-01-14 15:35:52 [info] dynamic-content-for-elementor::dce_updater Started 
2022-01-14 15:35:52 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Start  
2022-01-14 15:35:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.2.10',
  'to' => '2.2.11',
)]
2022-01-14 15:35:53 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default callback needs to run more 2 times 
2022-01-14 15:35:53 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Start (2 of 3, 67%) 
2022-01-14 15:35:53 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Start (3 of 3, 100%) 
2022-01-14 15:35:54 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Finished 
2022-01-14 15:35:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.2.10',
  'to' => '2.2.11',
)]

PHP: showing 8 of 8PHP: 2021-12-21 15:23:50 [warning X 4][/nas/content/live/hapstage/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-04 20:08:06 [warning X 4][/nas/content/live/hapstage/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 0 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-10 12:59:08 [warning X 19][/nas/content/live/hapstage/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-11 13:42:20 [error X 1][/nas/content/live/hapstage/wp-content/plugins/elementor/includes/plugin.php::862] Uncaught Error: Class "Elementor\Data\V2\Manager" not found in /nas/content/live/hapstage/wp-content/plugins/elementor/includes/plugin.php:862
Stack trace:
#0 /nas/content/live/hapstage/wp-content/plugins/elementor/includes/plugin.php(609): Elementor\Plugin->__construct()
#1 /nas/content/live/hapstage/wp-content/plugins/elementor/includes/plugin.php(878): Elementor\Plugin::instance()
#2 /nas/content/live/hapstage/wp-content/plugins/elementor/elementor.php(54): require('/nas/content/li...')
#3 /nas/content/live/hapstage/wp-admin/includes/plugin.php(2286): include_once('/nas/content/li...')
#4 /nas/content/live/hapstage/wp-admin/includes/plugin.php(668): plugin_sandbox_scrape('elementor/eleme...')
#5 /nas/content/live/hapstage/wp-admin/update.php(85): activate_plugin('elementor/eleme...', '', false, true)
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-11 13:42:22 [error X 1][/nas/content/live/hapstage/wp-content/plugins/elementor/includes/plugin.php::862] Uncaught Error: Class "Elementor\Data\V2\Manager" not found in /nas/content/live/hapstage/wp-content/plugins/elementor/includes/plugin.php:862
Stack trace:
#0 /nas/content/live/hapstage/wp-content/plugins/elementor/includes/plugin.php(609): Elementor\Plugin->__construct()
#1 /nas/content/live/hapstage/wp-content/plugins/elementor/includes/plugin.php(878): Elementor\Plugin::instance()
#2 /nas/content/live/hapstage/wp-content/plugins/elementor/elementor.php(54): require('/nas/content/li...')
#3 /nas/content/live/hapstage/wp-admin/update.php(100): include('/nas/content/li...')
#4 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-11 15:43:09 [warning X 1][/nas/content/live/hapstage/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-14 16:03:55 [notice X 194][/nas/content/live/hapstage/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-14 16:44:45 [warning X 2][/nas/content/live/hapstage/wp-content/plugins/elementor-pro/license/updater.php::83] Undefined array key "new_version" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
	Ele Custom Skin: Compatible
	Ele Custom Skin Pro: Compatible
	Elementor Pro: Compatible
	Happy Elementor Addons: Compatible
	Happy Elementor Addons Pro: Compatible
	OoohBoi Steroids for Elementor: Compatible
	Piotnet Addons For Elementor Pro: Compatible
	The Plus Addons for Elementor: Compatible
	The Plus Addons for Elementor - Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
	Ele Custom Skin: Compatible
	Ele Custom Skin Pro: Compatible
	Happy Elementor Addons: Compatible
	Happy Elementor Addons Pro: Compatible
	OoohBoi Steroids for Elementor: Compatible
	Piotnet Addons For Elementor Pro: Compatible
	The Plus Addons for Elementor: Compatible
	The Plus Addons for Elementor - Pro: Incompatible

**Comment by DigitalBerry** [comment]
Is this info safe on an open site?

**Comment by dudaster** [comment]
it should be. let me know if there are any issues!
