### ISSUE TITLE
critical error when ele custom skin pro is active

### ISSUE THREAD

**Issue by modernmindsnl** [dudaster/ele-custom-skin#707]
![image](https://user-images.githubusercontent.com/21106409/157247971-0bee5f1f-35e7-4537-b527-a70261776062.png)
On production this happens when the plugin is active with the latest elementor.
Conflict seems to exist: with elementor-pro/modules/theme-builder/classes/conditions-manager.php

When the plugin ele custom skin pro is deactivated the layout reverts to what it needs to be, however I miss the pro functionality elsewhere:
![image](https://user-images.githubusercontent.com/21106409/157248249-8a674ddb-74e5-4a70-8b47-2d09ac954080.png)

**Plugins:**
Elementor 3.5.6
Ele custom skin 3.2.2
Ele custom skin pro 3.1.4

**Comment by dudaster** [comment]
Can you paste the error you get here?

**Comment by losegehtz** [comment]
same issue 

error log:

[23-Mar-2022 09:34:48 UTC] PHP Fatal error:  Uncaught Error: Class 'Elementor\Scheme_Color' not found in /www/htdocs/w01998cc/asdasd.com/wp-content/plugins/ele-custom-skin-pro/skin/skin-custom.php:634
Stack trace:
#0 /www/htdocs/w01998cc/asdasd.com/wp-includes/class-wp-hook.php(287): {closure}(Object(ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS))
#1 /www/htdocs/w01998cc/asdasd.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /www/htdocs/w01998cc/asdasd.com/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /www/htdocs/w01998cc/asdasd.com/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(55): do_action('ECS_after_style...', Object(ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS))
#4 /www/htdocs/w01998cc/asdasd.com/wp-includes/class-wp-hook.php(289): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->register_navigation_design_controls(Object(ElementorPro\Modules\Posts\Widgets\Posts))
#5 /www/htdocs/w01998cc/asdasd.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_fi in /www/htdocs/w01998cc/asdasd.com/wp-content/plugins/ele-custom-skin-pro/skin/skin-custom.php on line 634


in addition system info says

Ele Custom Skin | Incompatible


environment

WP Version: | 5.9.2
Child Theme: | Yes |  
Parent Theme Name: | Astra |  
Parent Theme Version: | 3.7.9

[Ele Custom Skin] - 3.1.4
[Ele Custom Skin Pro] - 3.0.0
[Elementor] - 3.6.0
[Elementor Pro] - 3.6.4

**Comment by frednetk** [comment]
Same issue with latest versions of both.
Elementor 3.6.1 (but i have same problems also with 3.6.0)
Elementor Pro 3.6.4
Ele custom skin 3.1.4
Ele custom skin pro 3.2.3
Hello theme

Fatal error, if i try to deactivate the pro and reactivate, and purge cache, fatal error disappear but the elementor builder load forever.
It's working only if i donwgrade elementor to previous version 3.5.6

157026#0: *1286457 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Class 'Elementor\Scheme_Color' not found in [/var/www/vhosts/gbvsas.it/httpdocs/wp-content/plugins/ele-custom-skin-pro/skin/skin-custom.php](https://ru001604.arubabiz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-content%2Fplugins%2Fele-custom-skin-pro%2Fskin&subscriptionId=189&file=skin-custom.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F189):634
Stack trace:
#0 [/var/www/vhosts/gbvsas.it/httpdocs/wp-includes/class-wp-hook.php](https://ru001604.arubabiz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-includes&subscriptionId=189&file=class-wp-hook.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F189)(307): {closure}()
#1 [/var/www/vhosts/gbvsas.it/httpdocs/wp-includes/class-wp-hook.php](https://ru001604.arubabiz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-includes&subscriptionId=189&file=class-wp-hook.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F189)(331): WP_Hook->apply_filters()
#2 [/var/www/vhosts/gbvsas.it/httpdocs/wp-includes/plugin.php](https://ru001604.arubabiz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-includes&subscriptionId=189&file=plugin.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F189)(474): WP_Hook->do_action()
#3 [/var/www/vhosts/gbvsas.it/httpdocs/wp-content/plugins/ele-custom-skin/skins/skin-custom.php](https://ru001604.arubabiz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-content%2Fplugins%2Fele-custom-skin%2Fskins&subscriptionId=189&file=skin-custom.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F189)(55): do_action()
#4 [/var/www/vhosts/gbvsas.it/httpdocs/wp-includes/class-wp-hook.php](https://ru001604.arubabiz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-includes&subscriptionId=189&file=class-wp-hook.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F189)(309): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->register_navigation_design_controls()
#5 [/var/www/vhosts/gbvsas.it/httpdocs/wp-includes/class-wp-hook.php](https://ru001604.arubabiz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-includes&subscriptionId=189&file=class-wp-hook.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F189)(331): WP_Hook->apply_filters()
#6 [/var/www/vhosts/gbvsas.it/httpdocs/wp-includes/plugin.php](https://ru001604.arubabiz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-includes&subscriptionId=189&file=plugin.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F189)(474): WP_Hook->do_action()
#7 /var/www/vhosts/gbvsas.it/httpdocs/wp-content/plugins/elementor/includes/base/con" while reading response header from upstream

**Comment by dudaster** [comment]
Have you tried the beta version?

**Comment by frednetk** [comment]
> Have you tried the beta version?

No, im waiting for the main release when will be out or fixed version, since elementor are changing so much rules on their way to containers, any new update. I Saw there is another issue on top about beta version with elementor not loading. Since i use elecustomskin on any project and over many sites, better wait. Thank you for the sopport to solve it (the problem seems to be related to the Ele custom skin pro version, because disable it make it work again).
