### ISSUE TITLE
issue- need help

### ISSUE THREAD

**Issue by StephBeic** [dudaster/ele-custom-skin#733]
Fatal error: Uncaught Error: Class 'Elementor\Scheme_Color' not found in /home/eicolleg/public_html/wp-content/plugins/ele-custom-skin-pro/skin/skin-custom.php:552 Stack trace: #0 /home/eicolleg/public_html/wp-includes/class-wp-hook.php(307): {closure}(Object(ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS)) #1 /home/eicolleg/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #2 /home/eicolleg/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #3 /home/eicolleg/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(55): do_action('ECS_after_style...', Object(ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS)) #4 /home/eicolleg/public_html/wp-includes/class-wp-hook.php(309): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->register_navigation_design_controls(Object(ElementorPro\Modules\Posts\Widgets\Posts)) #5 /home/eicolleg/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #6 /home/eicolleg/public_html/wp-includes/plugin.php(474): W in /home/eicolleg/public_html/wp-content/plugins/ele-custom-skin-pro/skin/skin-custom.php on line 552

**Comment by dudaster** [comment]
Does the beta solve the issue?
