### ISSUE TITLE
** Site crashing on pages with ECS

### ISSUE THREAD

**Issue by gilles008** [dudaster/ele-custom-skin#742]
Hi folks, we have a site's pages crashing with this error.  We have the latest version of ECS free (Version 3.1.5) as well as ECS Pro on this site. Any ideas?
NOTE: There are no errors when we roll back to  ECS free version 3.14 

Version 3.1.5 
An error of type E_ERROR was caused in line 34 of the file /home/customer/www/_domain-name_/public_html/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php. Error message: Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home/customer/www/_domain-name_/public_html/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php:34
Stack trace:
#0 /home/customer/www/_domain-name_/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(42): ECS_Admin_Bar_Menu::add_document('7380')
#1 /home/customer/www/s_domain-name_public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(393): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->admin_bar_menu()
#2 /home/customer/www/_domain-name_/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(575): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render_loop_footer()
#3 /home/customer/www/_domain-name_public_html/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render()
#4 /home/customer/www/_domain-name_/

**Comment by andredasilva** [comment]
Same here, Could you please provide link to download 3.14? Thank you

**Comment by gilles008** [comment]
> Same here, Could you please provide link to download 3.14? Thank you

@andredasilva ... this should help:

https://kinsta.com/knowledgebase/download-older-versions-of-wordpress-plugins/

**Comment by dudaster** [comment]
Guys this version is for the latest elementor version. Elementor is moving some stuff around base and pro and that’s why the errors.

https://wordpress.org/plugins/ele-custom-skin/advanced/

scroll down until you see a drop down with all the previous versions.

**Comment by andredasilva** [comment]
Thank you guys!

**Comment by gilles008** [comment]
@dudaster 
Thanks for piping in. Users always appreciate it when devs show their involvement. Keep it up. :)

any idea as to when this will be fixed?

**Comment by gilles008** [comment]
Hello?

**Comment by fabienlege** [comment]
+1 Same bug for me, Ele custom Skin completely break my website with this error !
All my plugins are up to date, including Elementor & Elementor pro.

Any news for a patch to this issue ?

**Comment by dudaster** [comment]
Working on it. Thanks for pointing it out!

**Comment by gilles008** [comment]
Greetings!
Just flagging that this critical bug was reported over three weeks ago.
What's the status? Can we have an ETA please? or should we move along to an alternate, supported plugin?
No pressure but knowing the status what your intentions are would help us greatly.
Cheers!

**Comment by serna3** [comment]
Hi everyone! 
Same error here..

_Fatal error: Uncaught Error: Call to a member function is_built_with_elementor() on bool in /homepages/24/d838949507/htdocs/app857817584/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php:34 Stack trace: #0 /homepages/24/d838949507/htdocs/app857817584/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(42): ECS_Admin_Bar_Menu::add_document('538') #1 /homepages/24/d838949507/htdocs/app857817584/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(393): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->admin_bar_menu() #2 /homepages/24/d838949507/htdocs/app857817584/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(575): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render_loop_footer() #3 /homepages/24/d838949507/htdocs/app857817584/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render() #4 /homepages/24/d838949507/htdocs/app857817584/wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_m in /homepages/24/d838949507/htdocs/app857817584/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php on line 34_

Any news about this?
Cheers!

**Comment by Frederic-C** [comment]
I hope a new version will be available soon. We are actually stuck with an old version of the plugin 🤞

**Comment by gilles008** [comment]
What gives? Is this bug being fixed? We purchased the Pro version and are hoping this issue will be dealt with. I think you'll agree we've all been very patient.

**Comment by AHDOnline** [comment]
Im glad I found this one to tag onto, I spent weeks getting a site ready to only have it stop working.  Downgrading the plugins doesnt seem to work for me anymore..  lifetime Pro user.

**Comment by dudaster** [comment]
Please dezactivate Ele Custom Skin then update Elementor and Elementor Pro to the latest version than make sure Ele Custom Skin is updated to the latest version and than activate it. Let me know if it works!

**Comment by AHDOnline** [comment]
This made no difference to my issues.

**Comment by dudaster** [comment]
Can you please use the contact form of the website and and give me access to the admin to take a look?

**Comment by serna3** [comment]
I do this
_> Please dezactivate Ele Custom Skin then update Elementor and Elementor Pro to the latest version than make sure Ele Custom Skin is updated to the latest version and than activate it. Let me know if it works!_
and still doesn't work.

**Comment by Eroan** [comment]
Hi, same issue here !

`Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home/customer/www/domain-name/public_html/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php:34`

Ele Custom Skin 3.1.6 and latest Elementor + Elementor Pro.

**Comment by garylevansjr** [comment]
For anyone stuck on this issue, here is a dirty patch:


ON line 34 of /ele-custom-skin/includes/admin-bar-menu.php

REPLACE  THIS
```
if ( ! \Elementor\Plugin::$instance->documents->get( $post_id )->is_built_with_elementor() ) {
			return '';
}
```
WITH THIS
```
if ( ! get_post_meta( $post_id, '_elementor_edit_mode', true ) ) {
			return '';
}

```

**Comment by gilles008** [comment]
@garylevansjr ... thanks so much for providing this temporary workaround.

@dudaster ... Why is this issue not being addressed? It has been almost four months since it was reported and there have been two releases which haven't addressed this debilitating problem.

What can we do to help you resolve this?

**Comment by bluantinoo** [comment]
Still no word from @dudaster ? this is really a huge issue!  Anyone knows an alternative to ECS?

**Comment by dudaster** [comment]
@bluantino I've posted the reason you are getting the error. Just deactivate ECS. Update the Elementor first and then activate ECS.

This issue would be fixed in the next version.

**Comment by dudaster** [comment]
You can try it now also:
[ele-custom-skin.zip](https://github.com/dudaster/ele-custom-skin/files/9307196/ele-custom-skin.zip)

**Comment by gilles008** [comment]
@dudaster ... The fix you recommend ("_Update the Elementor first and then activate ECS.")_.. Did not work. Another user here also reported this back in June.

When is the next version coming?
Cheers.

**Comment by aCiDeViL** [comment]
Is this problem fixed in the last update 3 days ago? 
It's safe now to update?
Thank you.

**Comment by aCiDeViL** [comment]
I update and is working fine, no problem. Thank you.

**Comment by gilles008** [comment]
From my tests, 
It appears the version of ECS in the zip file download link in this thread works BUT....
The version in the WP plugin repository still contains the problem code.
Is this correct?

**Comment by MeiUsername** [comment]
Is there still a known issue? Just update to Ele 3.1.7 and Elementor Pro 3.7.7 and getting a critical error on my site.

Stack trace: 
#0 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php(66): ECS_Loop_Conditions->register_sub_conditions()
 #1 /var/www/html/wp-content/plugins/ele-custom-skin/theme-builder/conditions/loop.php(67): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct()
 #2 /var/www/html/wp-includes/class-wp-hook.php(307): {closure}()
 #3 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
 #4 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action()
 #5 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(239): do_action()
 #6 /var/www/html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions()
 #7 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters( in /var/www/html/wp-content/plugins/ele-custom-skin/theme-builder/conditions/loop.php on line 39

Would greatly appreciate any assistance!

**Comment by pjcc21e** [comment]
Hello All! I have a site with the following:

Ele Custom Skin 3.1.6
Ele Custom Skin Pro 3.2.4
Elementor 3.8.1 
Elementor Pro 3.8.2

Everything is up to date except for Ele Custom Skin. I'm getting the same error that others have mentioned in their posts - Fatal error: Uncaught Error: Class 'ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS' not found. 

I realize that this is happening because Elementor is shifting around code between their base and pro versions. What is the current status of this on the ECS side? Is the only existing solution to avoid updating this plugin to the latest version? Advice is greatly appreciated. Thanks!
