### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by BureauMeteor** [dudaster/ele-custom-skin#757]
Hi friends and thank you very much for your great plugin!
I use it for making custom loops, but since today I have a Fatal Error that says :

Fatal error
: Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home/bureauf/www/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php:34 Stack trace: #0 /home/bureauf/www/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(42): ECS_Admin_Bar_Menu::add_document('615') #1 /home/bureauf/www/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(393): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->admin_bar_menu() #2 /home/bureauf/www/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(575): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render_loop_footer() #3 /home/bureauf/www/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render() #4 /home/bureauf/www/wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode() #5 /home/bureauf/www/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content() #6 /home/bureauf/www/wp-conten in
/home/bureauf/www/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php
on line
34

Can you help me please?
Thank you in advance!
GR

**Comment by BureauMeteor** [comment]
Hello,
I just noticed another error message that might enlighten you: Template File: No Templates for condition > /themes/hello-elementor/index.php

Thank you!
