### ISSUE TITLE
ECS Causing Fatal Error

### ISSUE THREAD

**Issue by writerstreamer** [dudaster/ele-custom-skin#763]
Am also getting the following error on the site. 

WordPress version 5.9.3
Current theme: Hello Elementor (version 2.5.0)
Current plugin: Ele Custom Skin (version 3.1.5)
PHP version 7.4.29

Error Details
=============
An error of type E_ERROR was caused in line 34 of the file /home/geekvibesnation/public_html/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php. Error message: Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home/geekvibesnation/public_html/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php:34
Stack trace:
#0 /home/geekvibesnation/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(42): ECS_Admin_Bar_Menu::add_document('100990')
#1 /home/geekvibesnation/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(393): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->admin_bar_menu()
#2 /home/geekvibesnation/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(575): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render_loop_footer()
#3 /home/geekvibesnation/public_html/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render()
#4 /home/geekvibesnation/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#5 /home/geekvibesnation/public_html/wp-content/plugins/e

**Comment by wasil-cz** [comment]
i'm getting this error too, after importing an exported Elementor Kit. 
it's because the templates obtain a new ID during import, while ECS refers to the old one.

i avoided the fatal error by adding this condition before line 34:

`if(!\Elementor\Plugin::$instance->documents->get( $post_id ))
			return '';`

it simply checks if the tested post ID is recognized by Elementor and quits if not.
