### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by teaqueue** [dudaster/ele-custom-skin#862]
Hi

I'm getting a Fatal Error. 
If I disable Ele Custom Skin Pro, this error disappears.

Error appears in Elementor, and page cannot be edited.
Error appears also on frontend.

----
Fatal error: Uncaught Error: Call to a member function get_main_meta() on null in /nas/content/live/itaccounts/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:468 Stack trace: #0 /nas/content/live/itaccounts/wp-content/plugins/ele-custom-skin-pro/modules/display-conditions.php(57): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->get_document_conditions(NULL) #1 /nas/content/live/itaccounts/wp-content/plugins/ele-custom-skin-pro/modules/display-conditions.php(23): ECS_Conditions_Manager->cache_conditions() #2 /nas/content/live/itaccounts/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(546): ECS_Conditions_Manager->__construct() #3 /nas/content/live/itaccounts/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render() #4 /nas/content/live/itaccounts/wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode() #5 /nas/content/live/itaccounts/wp-content/plugins/ele in /nas/content/live/itaccounts/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php on line 468

----

**Comment by teaqueue** [comment]
GitHub not allowing me to submit screengrabs.

**Comment by dudaster** [comment]
What version of Elementor and elementor,  Ele custom skin are you using?

**Comment by teaqueue** [comment]
Monthly update of plugins fixed this. So it was combination of last month's updates that broke it.

Now:
Elementor Pro - Version 3.7.7
Elementor - Version 3.7.8
ECS Pro - Version 3.2.4
ECS - Version 3.1.7

- Seems to work.
