### ISSUE TITLE
Ele Custom Skin plugin caused fatal error and made the whole website blank!

### ISSUE THREAD

**Issue by dev-mominul** [dudaster/ele-custom-skin#927]
Hello,

We're using your pro plugin on many of our client websites. Today it has just caught our attention that one of our client websites (thedammannteam.com) has gone completely blank due to your plugin. Later, we had to disable your plugin and site again.

We're concerned about why it's happening because we're using your plugin on many other client websites. We're looking forward to your help and resolution ASAP.

Here I'm pasting the error log from our server for your reference:

`[13-Dec-2023 18:19:45 UTC] PHP Fatal error:  Uncaught Error: Class "ElementorPro\Modules\Posts\Skins\Skin_Base" not found in /home/dammann3039/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php:16
Stack trace:
#0 /home/dammann3039/public_html/wp-content/plugins/ele-custom-skin/ele-custom-skin.php(45): require_once()
#1 /home/dammann3039/public_html/wp-includes/class-wp-hook.php(307): elecs_add_skins(Object(Elementor\Widgets_Manager))
#2 /home/dammann3039/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#3 /home/dammann3039/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 /home/dammann3039/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(138): do_action('elementor/widge...', Object(Elementor\Widgets_Manager))
#5 /home/dammann3039/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(328): Elementor\Widgets_Manager->init_widgets()
#6 /home/dammann3039/public_html/wp-content/plugins/elementor/includes/elements/column.php(1071): Elementor\Widgets_Manager->get_widget_types('shortcode')
#7 /home/dammann3039/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1420): Elementor\Element_Column->_get_default_child_type(Array)
#8 /home/dammann3039/public_html/wp-content/plugins/elementor/includes/base/element-base.php(340): Elementor\Element_Base->get_child_type(Array)
#9 /home/dammann3039/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1465): Elementor\Element_Base->add_child(Array)
#10 /home/dammann3039/public_html/wp-content/plugins/elementor/includes/base/element-base.php(300): Elementor\Element_Base->init_children()
#11 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/post.php(225): Elementor\Element_Base->get_children()
#12 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Column), Array, Array, Array, Array)
#13 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Column))
#14 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array)
#15 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/post.php(178): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Section))
#16 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/base.php(659): Elementor\Core\Files\CSS\Post->render_css()
#17 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#18 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/base.php(130): Elementor\Core\Files\Base->update_file()
#19 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/base.php(217): Elementor\Core\Files\CSS\Base->update()
#20 /home/dammann3039/public_html/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue()
#21 /home/dammann3039/public_html/wp-content/plugins/elementor/includes/frontend.php(676): Elementor\Core\Files\CSS\Post->enqueue()
#22 /home/dammann3039/public_html/wp-includes/class-wp-hook.php(307): Elementor\Frontend->enqueue_styles('')
#23 /home/dammann3039/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#24 /home/dammann3039/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#25 /home/dammann3039/public_html/wp-includes/script-loader.php(2115): do_action('wp_enqueue_scri...')
#26 /home/dammann3039/public_html/wp-includes/class-wp-hook.php(307): wp_enqueue_scripts('')
#27 /home/dammann3039/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#28 /home/dammann3039/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#29 /home/dammann3039/public_html/wp-includes/general-template.php(3042): do_action('wp_head')
#30 /home/dammann3039/public_html/wp-content/themes/astra/header.php(31): wp_head()
#31 /home/dammann3039/public_html/wp-includes/template.php(770): require_once('/home/dammann30...')
#32 /home/dammann3039/public_html/wp-includes/template.php(716): load_template('/home/dammann30...', true, Array)
#33 /home/dammann3039/public_html/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#34 /home/dammann3039/public_html/wp-content/themes/astra/page.php(20): get_header()
#35 /home/dammann3039/public_html/wp-includes/template-loader.php(106): include('/home/dammann30...')
#36 /home/dammann3039/public_html/wp-blog-header.php(19): require_once('/home/dammann30...')
#37 /home/dammann3039/public_html/index.php(17): require('/home/dammann30...')
#38 {main}
  thrown in /home/dammann3039/public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 16`

Thank you so much!

**Comment by Omegatcu** [comment]
Did you get a response?
I use it on many websites as well and I fear this project is abandoned.

**Comment by dev-mominul** [comment]
Unfortunately not yet.

**Comment by technoogies** [comment]
> Unfortunately not yet.

@dev-mominul I was about to purchase the pro plugin . . . Then I saw this. If this is where they handle support and how they respond, I have reservations. Did they ever contact you in some other way? Have you tried the contact form at [https://dudaster.com/contact/](https://dudaster.com/contact/) ?

**Comment by dev-mominul** [comment]
@technoogies They never responded to this or in any other way. And yes, I tried their contact form too. It looks like their support system is horrible!

**Comment by MTFR876** [comment]
The plugin says it hasn't been updated for 1 year. A bit of a worry. You would hope if they were shutting down they'd announce it.
